import React from 'react';
import { ScrollView, Text, TouchableOpacity, View } from 'react-native';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { LineChart, PieChart } from 'react-native-chart-kit';
import { styles, colors } from './theme/styles';

const Tab = createBottomTabNavigator();
const Button = ({children, onPress}: any) => <TouchableOpacity accessibilityRole="button" style={styles.button} onPress={onPress}><Text style={styles.buttonText}>{children}</Text></TouchableOpacity>;
const Card = ({title, children}: any) => <View style={styles.card}><Text style={styles.cardTitle}>{title}</Text>{children}</View>;

export function SplashScreen({navigation}: any){ React.useEffect(()=>{setTimeout(()=>navigation.replace('Welcome'),500)},[]); return <View style={styles.center}><Text style={styles.logo}>GoTradePal</Text><Text style={styles.muted}>Your Personal Economic OS</Text></View> }
export function WelcomeScreen({navigation}: any){ return <View style={styles.center}><Text style={styles.hero}>Grow money, skills, and opportunity with AI.</Text><Button onPress={()=>navigation.navigate('Auth')}>Get Started</Button></View> }
export function AuthScreen({navigation}: any){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Sign up or log in</Text><Text style={styles.muted}>Secure JWT auth, password hashing, and audit logging are backend-ready.</Text><Button onPress={()=>navigation.navigate('ProfileSetup')}>Continue Demo</Button></ScrollView> }
export function ProfileSetupScreen({navigation}: any){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Economic Profile</Text><Card title="Tell us about you"><Text>Skills, education, experience, goals, income level, and interests power your roadmap.</Text></Card><Button onPress={()=>navigation.navigate('Assessment')}>Start AI Assessment</Button></ScrollView> }
export function AssessmentScreen({navigation}: any){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>AI Economic Assessment</Text><Card title="Roadmap"><Text>1. Stabilize finances\n2. Learn marketable skills\n3. Match opportunities\n4. Track progress weekly</Text></Card><Button onPress={()=>navigation.replace('Main')}>Open Dashboard</Button></ScrollView> }
function Dashboard(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Dashboard</Text><Card title="Financial Health Score"><Text style={styles.score}>82</Text><LineChart data={{labels:['Jan','Feb','Mar','Apr'],datasets:[{data:[55,62,74,82]}]}} width={320} height={180} yAxisSuffix="" chartConfig={chart}/></Card><Card title="AI Recommendations"><Text>Save 15% this month • Finish Digital Freelancing • Apply to 2 remote projects</Text></Card><Card title="Goals"><Text>Emergency fund: 64% complete</Text></Card></ScrollView> }
function Chat(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>AI Chat Assistant</Text>{['Financial Coach','Learning Agent','Career Agent','Business Agent','Research Agent'].map(a=><Card key={a} title={a}><Text>Ask for guidance, plans, explanations, and next best actions.</Text></Card>)}</ScrollView> }
function Learning(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Learning Academy</Text>{['Budgeting Foundations','Digital Freelancing','AI for Small Business'].map(c=><Card key={c} title={c}><Text>Course progress, certificates, and skill growth tracking.</Text></Card>)}</ScrollView> }
function Finance(){ const pie=[{name:'Housing',amount:40,color:'#2563EB',legendFontColor:'#64748B',legendFontSize:12},{name:'Food',amount:25,color:'#14B8A6',legendFontColor:'#64748B',legendFontSize:12},{name:'Savings',amount:35,color:'#22C55E',legendFontColor:'#64748B',legendFontSize:12}]; return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Financial Dashboard</Text><Card title="Monthly Cashflow"><LineChart data={{labels:['W1','W2','W3','W4'],datasets:[{data:[300,520,460,720]}]}} width={320} height={180} chartConfig={chart}/></Card><Card title="Spending Mix"><PieChart data={pie} width={320} height={180} accessor="amount" backgroundColor="transparent" paddingLeft="8" chartConfig={chart}/></Card><Button>Export Report</Button></ScrollView> }
function Opportunities(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Opportunity Marketplace</Text>{['Jobs','Projects','Businesses'].map(x=><Card key={x} title={x}><Text>AI-matched global opportunities based on goals and skills.</Text></Card>)}</ScrollView> }
function Community(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Community</Text><Card title="Peer growth circles"><Text>Learn with accountability and share safe, moderated wins.</Text></Card></ScrollView> }
function Settings(){ return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Settings</Text><Card title="Security & privacy"><Text>Manage account, data export, notifications, and consent.</Text></Card></ScrollView> }
export function MainTabs(){ return <Tab.Navigator><Tab.Screen name="Home" component={Dashboard}/><Tab.Screen name="AI" component={Chat}/><Tab.Screen name="Learn" component={Learning}/><Tab.Screen name="Finance" component={Finance}/><Tab.Screen name="Market" component={Opportunities}/><Tab.Screen name="Community" component={Community}/><Tab.Screen name="Settings" component={Settings}/></Tab.Navigator> }
const chart={backgroundGradientFrom:colors.card,backgroundGradientTo:colors.card,color:(o=1)=>`rgba(37,99,235,${o})`,labelColor:()=>colors.muted};
